# Generated by Django 2.2.1 on 2019-10-07 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Colaborador'),
            preserve_default=False,
        ),
    ]
