# Generated by Django 2.2.1 on 2019-10-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191030_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('chegada', models.TimeField()),
                ('saida', models.TimeField()),
                ('tempo_intervalo', models.DurationField(default='1:00:00')),
                ('horas_trabalhadas', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='is_estagiario',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Ponto',
        ),
        migrations.AddField(
            model_name='pontodiario',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Colaborador'),
        ),
    ]
